Repository onflow/flow-cadut, pull requests merged in 2022-08, with the labels that each got.

#111 PKG -- [flow-cadut-generator] Add named exports to generated index files
  .changeset/stupid-berries-invent.md
  package-lock.json
  package.json
  packages/flow-cadut-generator/package.json
  packages/flow-cadut-generator/src/templates/index.js
  packages/flow-cadut-generator/src/templates/package.hbs
  packages/flow-cadut/package.json
  packages/generator-test/package.json
  packages/generator-test/src/generated/contracts/index.js
  packages/generator-test/src/generated/index.js
  packages/generator-test/src/generated/scripts/index.js
  packages/generator-test/src/generated/transactions/index.js
Labels: enhancement

#113 PKG -- [flow-cadut] Add support for optional complex types
  .changeset/yellow-hairs-fetch.md
  packages/flow-cadut/src/args.js
  packages/flow-cadut/src/type-checker.js
  packages/flow-cadut/tests/args.test.js
Labels: bug

#107 PKG -- [flow-cadut] Add valid domain checking to paths according to provided argument type
  .changeset/rich-spies-draw.md
  packages/flow-cadut/src/args.js
  packages/flow-cadut/src/fixer.js
  packages/flow-cadut/tests/fixer.test.js
Labels: enhancement

#125 Updated simple-git dependency, addressing high sev vulnerability
  package-lock.json
  packages/flow-cadut/package.json
Labels: good first issue, dependencies
